style: fixed shell lint errors

diff --git a/.polyfills/copy b/.polyfills/copy
--- a/.polyfills/copy
+++ b/.polyfills/copy
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-command -V pbcopy > /dev/null 2>&1 && pbcopy "$@"; exit 0 # MacOS
-command -V xsel > /dev/null 2>&1 && xsel --input --clipboard "$@"; exit 0 # Unix/Linux
-command -V xclip > /dev/null 2>&1 && xclip -in -selection clipboard "$@"; exit 0 # Unix/Linux
-command -V wl-copy > /dev/null 2>&1 && wl-copy "$@"; exit 0 # Wayland
-command -V powershell.exe > /dev/null 2>&1 && powershell.exe Set-Clipboard "$@"; exit 0 # WSL
+command -V pbcopy > /dev/null 2>&1 && { pbcopy "$@"; exit 0; } # MacOS
+command -V xsel > /dev/null 2>&1 && { xsel --input --clipboard "$@"; exit 0; } # Unix/Linux
+command -V xclip > /dev/null 2>&1 && { xclip -in -selection clipboard "$@"; exit 0; } # Unix/Linux
+command -V wl-copy > /dev/null 2>&1 && { wl-copy "$@"; exit 0; } # Wayland
+command -V powershell.exe > /dev/null 2>&1 && { powershell.exe Set-Clipboard "$@"; exit 0; } # WSL
 
-echo "unable to find any clipboard tool"; exit 1
+echo "unable to find any clipboard tool"
+exit 1
 
 # vim: ft=sh
