refactor: single-user nix
Needed specially for work, because CISO there does the cheap move of
shooting first, asking questions later.

Signed-off-by: William Artero <git@artero.dev>

diff --git a/.chezmoiscripts/run_onchange_after_01-nix.sh.tmpl b/.chezmoiscripts/run_onchange_after_01-nix.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_01-nix.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_01-nix.sh.tmpl
@@ -12,7 +12,33 @@ printf "\e[1;33mNix\e[0m\n"
 # skip if nix is installed
 command -v nix >/dev/null 2>&1 && exit
 
-curl -L https://nixos.org/nix/install | sh -s
+if [ "${CHEZMOI_OS:-}" != "darwin" ]; then
+  curl -L https://nixos.org/nix/install | sh -s
+else
+  TMP=$(mktemp -d)
+  OLD_PWD="${PWD}"
+  cd "${TMP}" || exit
+  trap 'cd "${OLD_PWD}"; rm -rf "${TMP}"' EXIT
+
+  # convert to a single-user install
+  if grep -q "build-users-group" /etc/nix/nix.conf; then
+    # remove the build-users-group from the global nix configuration, otherwise
+    # it tries to use the daemon socket
+    awk '/^build-users-group/ {next};1' /etc/nix/nix.conf > nix.conf
+    # shellcheck disable=SC2002
+    cat "nix.conf" | sudo tee "$(realpath /etc/nix/nix.conf)"
+    # ensure the current user is part of the _developer group
+    sudo dscl . append /Groups/_developer GroupMembership "$(whoami)"
+    # hostile takeover! :D
+    sudo chown -R "$(id -u):_developer" /nix
+    # cleanup the daemon
+    sudo launchctl bootout system/org.nixos.nix-daemon || true
+    sudo rm /Library/LaunchDaemons/org.nixos.nix-daemon.plist || true
+    unset NIX_REMOTE # no daemon
+  fi
+fi
+
+
 
 # force loading on the current shell and bootstrap the installation
 unset __ETC_PROFILE_NIX_SOURCED
